# Generated by Django 3.0.7 on 2020-06-18 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cli_nom', models.CharField(max_length=30, null=True)),
                ('cli_ape', models.CharField(max_length=150, null=True)),
                ('cli_email', models.CharField(max_length=254)),
                ('cli_pais', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('gen_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('gen_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('idi_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('idi_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('jue_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('jue_titulo', models.CharField(max_length=50)),
                ('jue_desarrollador', models.CharField(max_length=50)),
                ('jue_editor', models.CharField(max_length=50)),
                ('jue_franquicia', models.CharField(max_length=50)),
                ('jue_precio', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('mod_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mod_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pag_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pag_tipo', models.CharField(max_length=20)),
                ('pag_permitido', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('ord_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ord_fecha_ord', models.DateField(auto_now=True)),
                ('ord_fecha_pago', models.DateField()),
                ('ord_cli_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Cliente')),
                ('ord_pag_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Pago')),
            ],
        ),
        migrations.CreateModel(
            name='Mod_Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mxj_idi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Modalidad')),
                ('mxj_jue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Juego')),
            ],
        ),
        migrations.CreateModel(
            name='Idioma_Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ixj_idi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Idioma')),
                ('ixj_jue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Juego')),
            ],
        ),
        migrations.CreateModel(
            name='Genero_Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gxj_gen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Genero')),
                ('gxj_jue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Juego')),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_orden',
            fields=[
                ('dxo_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dxo_jue_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Juego')),
                ('dxo_ord_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Orden')),
            ],
        ),
    ]
